### ISSUE TITLE
API Location

### ISSUE THREAD

**Issue by Mr00Anderson** [zKillboard/evewho#17]
I saw a mention of query restrictions and API access for things.  Where would I find documentation for evewho API.  I was interested in writing a tool to do image analysis on portraits and names to create a EveWhosAlt.com or something with a connections based on criteria.  So really data would really be cached once periodically and used to build analysis cache for representation.

**Comment by Dusty-Meg** [comment]
In the MOTD of this repo

https://github.com/zKillboard/evewho#api
